id: P000818
initial_creation_type: ocr
created_at: 6/04/2021
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS20272
  title: ཧྥ་རན་སིར་ཉར་བའི་ཏུན་ཧོང་ཡིག་རྙིང་ཤོག་དྲིལ་བཤུས་ཡིག་ཕྱོགས་བསྒྲིགས། དེབ་དང་པོ
  volumes:
    d4b08791ebc6479a8af427106b90b30d:
      image_group_id: I8LS20274
      title: ''
      base_file: v001.txt
  author: ''
